
//***************************************************************************
//*																			*
//*																			*
//*																			*
//*  DO NOT MODIFY THIS FILE - IT IS AUTOGENERATED FROM THE DRIVER DESIGN   *
//*																			*
//*																			*
//*																			*
//***************************************************************************

using System;
using System.Drawing;
using System.ServiceModel;
using System.Windows.Forms;
using System.Diagnostics.CodeAnalysis;
using System.CodeDom.Compiler;
using CNL.IPSecurityCenter.Driver;
using CNL.IPSecurityCenter.Driver.Attributes;
using CNL.IPSecurityCenter.Driver.ServiceLocation;
using CNL.IPSecurityCenter.Driver.Video;
using CNL.IPSecurityCenter.Driver.Video.DeviceConnection;
using CNL.IPSecurityCenter.Driver.Video.Playback;
using CNL.IPSecurityCenter.Driver.Video.Export;
using CNL.IPSecurityCenter.Driver.Ptz;
using VideoDeviceInterfaceDescriptor = CNL.IPSecurityCenter.Driver.Video.DeviceConnection.DeviceInterfaceDescriptor;



namespace Edge360.IPSC.Driver.Axis
{
        
	[
		GeneratedCode("Driver.Design", "4.9.2.0"),
		SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces"),
        ServiceContract,
        Manufacturer(@"Axis Communications", @"Axis offers intelligent security solutions that enable a smarter, safer world. As the global market leader in network video, Axis is driving the industry by continually launching innovative network products based on an open platform - delivering high value to customers through a global partner network.", @"http://www.axis.com/", @"http://www.axis.com/us/en/learning-and-support", @"Edge360.IPSC.Driver.Axis.Images.manufacturerlogo.jpg", @"Axis Communications", typeof(IVideoServer)),
        Product(@"AXIS Server", @"AXIS P32 Series consists of vandal resistant cameras for indoor and outdoor installation. They meet both the quality and cost demands of the market, while at the same time being easy to use and operate.", @"http://www.axis.com/us/en/products/axis-p32-series", DeviceCategoryType.CCTV, @"Edge360.IPSC.Driver.Axis.Images.manufacturerlogo.jpg", @"AXIS", typeof(IVideoServer)),
        DisplayImage(DisplayImageSize.Image16x16, @"Edge360.IPSC.Driver.Axis.Images.server16.png", typeof(IVideoServer)),
        DisplayImage(DisplayImageSize.Image24x24, @"Edge360.IPSC.Driver.Axis.Images.server24.png", typeof(IVideoServer)),
        DisplayImage(DisplayImageSize.Image32x32, @"Edge360.IPSC.Driver.Axis.Images.server32.png", typeof(IVideoServer)),
        DisplayImage(DisplayImageSize.Image64x64, @"Edge360.IPSC.Driver.Axis.Images.server64.png", typeof(IVideoServer)),
        VideoControl(typeof(VideoServerVideoControl))    
    ]
    public interface IVideoServer : 
		IDevice

		//Server device interfaces
		, ISecureDevice 		, INetworkedDevice 						, IVideoExport		, IPresetsServer
		//Client device interfaces
				
		    
	{
		// -- events

		
		// -- properties

		
		/// <summary>
        /// 
        /// </summary>
        [CategoryPropertiesAttribute]
		        [DisplayName("Edge360.IPSC.Driver.Axis.Design.driverdesign.Strings", "DisplayNamezoomSpeed", typeof(IVideoServer))]
        [Description("Edge360.IPSC.Driver.Axis.Design.driverdesign.Strings", "DescriptionzoomSpeed", typeof(IVideoServer))]
						 [DeviceWizard] 		 [System.ComponentModel.DefaultValue(200)]         int zoomSpeed 
		{  
			 [OperationContract]  get; 
			 [OperationContract]  set; 
		}

		
		// -- methods

			}
}


namespace Edge360.IPSC.Driver.Axis
{
        
	[
		GeneratedCode("Driver.Design", "4.9.2.0"),
		SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces"),
        ServiceContract,
        Manufacturer(@"AXIS Communications", @"Axis offers a wide portfolio of IP-based products and solutions for security and video surveillance.", @"http://www.axis.com/us/en", @"http://www.axis.com/us/en/learning-and-support", @"Edge360.IPSC.Driver.Axis.Images.manufacturerlogo.jpg", @"AXIS Communications", typeof(IVideoCamera)),
        Product(@"AXIS Camera", @"Simply attractive. Streamlined and versatile varifocal fixed domes.", @"http://www.axis.com/us/en/products/axis-p32-series", DeviceCategoryType.CCTV, @"Edge360.IPSC.Driver.Axis.Images.manufacturerlogo.jpg", @"AXIS Network Camera", typeof(IVideoCamera)),
        DisplayImage(DisplayImageSize.Image16x16, @"Edge360.IPSC.Driver.Axis.Images.camera16.png", typeof(IVideoCamera)),
        DisplayImage(DisplayImageSize.Image24x24, @"Edge360.IPSC.Driver.Axis.Images.camera24.png", typeof(IVideoCamera)),
        DisplayImage(DisplayImageSize.Image32x32, @"Edge360.IPSC.Driver.Axis.Images.camera32.png", typeof(IVideoCamera)),
        DisplayImage(DisplayImageSize.Image64x64, @"Edge360.IPSC.Driver.Axis.Images.camera64.png", typeof(IVideoCamera)),
           
    ]
    public interface IVideoCamera : 
		IDevice

		//Server device interfaces
												
		//Client device interfaces
		, IPresetsDevice		, IPtzDevice
		    
	{
		// -- events

		
		// -- properties

		
		// -- methods

			}
}

