//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edge360.IPSC.Driver.Axis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edge360.IPSC.Driver.Axis.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video feed unavailable because connection manager is unreachable..
        /// </summary>
        internal static string ConnectionManagerUnreachable {
            get {
                return ResourceManager.GetString("ConnectionManagerUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the device. An error occurred during connection..
        /// </summary>
        internal static string DeviceConnectionFailed {
            get {
                return ResourceManager.GetString("DeviceConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password..
        /// </summary>
        internal static string DeviceInvalidCredentials {
            get {
                return ResourceManager.GetString("DeviceInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manufacturer&apos;s SDK for this driver is not installed..
        /// </summary>
        internal static string DeviceSdkMissing {
            get {
                return ResourceManager.GetString("DeviceSdkMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the device was refused. The IP address or port for the device may be incorrect..
        /// </summary>
        internal static string DeviceUnavailable {
            get {
                return ResourceManager.GetString("DeviceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device address (IP or host) cannot be reached..
        /// </summary>
        internal static string DeviceUnreachable {
            get {
                return ResourceManager.GetString("DeviceUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error message could not be found for the problem that occurred..
        /// </summary>
        internal static string ErrorNotFound {
            get {
                return ResourceManager.GetString("ErrorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video could not be exported because connection to the device was refused. The IP address or port for the device may be incorrect..
        /// </summary>
        internal static string ExportVideoDeviceUnavailable {
            get {
                return ResourceManager.GetString("ExportVideoDeviceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video could not be exported because the device address (IP or host) cannot be reached..
        /// </summary>
        internal static string ExportVideoDeviceUnreachable {
            get {
                return ResourceManager.GetString("ExportVideoDeviceUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video could not be exported because an error occurred during the export procedure..
        /// </summary>
        internal static string ExportVideoError {
            get {
                return ResourceManager.GetString("ExportVideoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video could not be exported because the user name or password is incorrect..
        /// </summary>
        internal static string ExportVideoIncorrectCredentials {
            get {
                return ResourceManager.GetString("ExportVideoIncorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video could not be exported because recorded video is not available for the selected time..
        /// </summary>
        internal static string ExportVideoRecordingNotAvailable {
            get {
                return ResourceManager.GetString("ExportVideoRecordingNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video could not be exported because the manufacturer&apos;s SDK for this driver is not installed..
        /// </summary>
        internal static string ExportVideoSdkMissing {
            get {
                return ResourceManager.GetString("ExportVideoSdkMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live video could not be displayed for this camera because the camera is not connected to a video server in IPSecurityCenter..
        /// </summary>
        internal static string LiveVideoCameraNotConnected {
            get {
                return ResourceManager.GetString("LiveVideoCameraNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live video could not be displayed for this camera because a connection to the video server was refused. The IP address or port for the device may be incorrect..
        /// </summary>
        internal static string LiveVideoDeviceUnavailable {
            get {
                return ResourceManager.GetString("LiveVideoDeviceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live video could not be displayed for this camera because the device address (IP or host) cannot be reached..
        /// </summary>
        internal static string LiveVideoDeviceUnreachable {
            get {
                return ResourceManager.GetString("LiveVideoDeviceUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live video could not be displayed for this camera because the video feed has been lost..
        /// </summary>
        internal static string LiveVideoFeedLost {
            get {
                return ResourceManager.GetString("LiveVideoFeedLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live video could not be displayed for this camera because a live feed is not available for this camera..
        /// </summary>
        internal static string LiveVideoFeedNotAvailable {
            get {
                return ResourceManager.GetString("LiveVideoFeedNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live video could not be displayed for this camera because the user name or password is incorrect..
        /// </summary>
        internal static string LiveVideoInvalidCredentials {
            get {
                return ResourceManager.GetString("LiveVideoInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live video could not be displayed for this camera because the maximum number of connections to the device has been reached..
        /// </summary>
        internal static string LiveVideoMaxConnectionsReached {
            get {
                return ResourceManager.GetString("LiveVideoMaxConnectionsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live video could not be displayed for this camera because live video is not supported by this camera..
        /// </summary>
        internal static string LiveVideoNotSupported {
            get {
                return ResourceManager.GetString("LiveVideoNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live video could not be displayed for this camera because the manufacturer&apos;s SDK for this driver is not installed..
        /// </summary>
        internal static string LiveVideoSdkMissing {
            get {
                return ResourceManager.GetString("LiveVideoSdkMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live video could not be displayed for this camera because the video server is not compatible with this driver..
        /// </summary>
        internal static string LiveVideoServerIncompatible {
            get {
                return ResourceManager.GetString("LiveVideoServerIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded video could not be displayed for this camera because the camera is not connected to a video server in IPSecurityCenter..
        /// </summary>
        internal static string RecordedVideoCameraNotConnected {
            get {
                return ResourceManager.GetString("RecordedVideoCameraNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live video could not be displayed for this camera because a connection to the video server was refused. The IP address or port for the device may be incorrect..
        /// </summary>
        internal static string RecordedVideoDeviceUnavailable {
            get {
                return ResourceManager.GetString("RecordedVideoDeviceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded video could not be displayed for this camera because the device address (IP or host) cannot be reached..
        /// </summary>
        internal static string RecordedVideoDeviceUnreachable {
            get {
                return ResourceManager.GetString("RecordedVideoDeviceUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded video could not be displayed for this camera because the video feed has been lost..
        /// </summary>
        internal static string RecordedVideoFeedLost {
            get {
                return ResourceManager.GetString("RecordedVideoFeedLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded video could not be displayed for this camera because recorded video is not available for this camera..
        /// </summary>
        internal static string RecordedVideoFeedNotAvailable {
            get {
                return ResourceManager.GetString("RecordedVideoFeedNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded video could not be displayed for this camera because the user name or password is incorrect..
        /// </summary>
        internal static string RecordedVideoInvalidCredentials {
            get {
                return ResourceManager.GetString("RecordedVideoInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded video could not be displayed for this camera because the maximum number of connections to the device has been reached..
        /// </summary>
        internal static string RecordedVideoMaxConnectionsReached {
            get {
                return ResourceManager.GetString("RecordedVideoMaxConnectionsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded video could not be displayed for this camera because recorded video is not supported by this camera..
        /// </summary>
        internal static string RecordedVideoNotSupported {
            get {
                return ResourceManager.GetString("RecordedVideoNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded video could not be displayed for this camera because the manufacturer&apos;s SDK for this driver is not installed..
        /// </summary>
        internal static string RecordedVideoSdkMissing {
            get {
                return ResourceManager.GetString("RecordedVideoSdkMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded video could not be displayed for this camera because the video server is not compatible with this driver..
        /// </summary>
        internal static string RecordedVideoServerIncompatble {
            get {
                return ResourceManager.GetString("RecordedVideoServerIncompatble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video feed could not be displayed..
        /// </summary>
        internal static string VideoFeedNotAvailable {
            get {
                return ResourceManager.GetString("VideoFeedNotAvailable", resourceCulture);
            }
        }
    }
}
